apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-error-map-backend
data:
  error_mapping.yaml: >
    error_mapping:
      502: 401

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-error-map-backend
spec:
  selector:
    matchLabels:
      app: custom-error-map-backend
  template:
    metadata:
      labels:
        app: custom-error-map-backend
    spec:
      containers:
      - name: custom-error-map-backend
        image: alantang888/custom-error-map-backend:1.0.0
        env:
        - name: CONFIG_PATH
          value: /config/error_mapping.yaml
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: error-mapping
          mountPath: /config
      volumes:
      - name: error-mapping
        configMap:
          name: custom-error-map-backend

---
apiVersion: v1
kind: Service
metadata:
  name: custom-error-map-backend
  labels:
    app: custom-error-map-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: custom-error-map-backend
